### ISSUE TITLE
Continuous integration server? 

### ISSUE THREAD

**Issue by stereobooster** [NickolasVashchenko/stopgap_13632#1]
Travis or CircleCI

**Comment by NikolayRys** [comment]
It's Travis currently. https://travis-ci.org/NickolasVashchenko/stopgap_13632
And appveyour that you've recommended: https://ci.appveyor.com/project/NickolasVashchenko/stopgap-13632
Are you proposing to consider the Circle?

**Comment by stereobooster** [comment]
Ah... badge is in the bottom page. I got used to badges in the top

**Comment by NikolayRys** [comment]
Hm, indeed :) I'll move it up
