### ISSUE TITLE
Segmentation fault  on armv7hl

### ISSUE THREAD

**Issue by junaruga** [NickolasVashchenko/stopgap_13632#2]
Hello,

I am maintaining `puma`'s RPM package on Fedora Project.
And I built `puma` v3.9.1 with a patch for `stopgap_13632` (https://github.com/puma/puma/commit/9141613) on not only x86_64, but also several architectures, on Ruby 2.4.1.

On architecture `armv7hl`, I always got a error during `bundle exec rake`.

https://koji.fedoraproject.org/koji/taskinfo?taskID=21149641
https://kojipkgs.fedoraproject.org//work/tasks/9661/21149661/build.log

```
/builddir/build/BUILD/puma-3.9.1/usr/share/gems/gems/puma-3.9.1/lib/puma/reactor.rb:152: [BUG] Segmentation fault at 0x000001
ruby 2.4.1p111 (2017-03-22 revision 58053) [armv7hl-linux]
-- Control frame information -----------------------------------------------
c:0028 p:---- s:0147 e:000146 CFUNC  :initialize
c:0027 p:---- s:0144 e:000143 CFUNC  :new
c:0026 p:0015 s:0140 E:ffffd968 METHOD /builddir/build/BUILD/puma-3.9.1/usr/share/gems/gems/puma-3.9.1/lib/puma/reactor.rb:152
c:0025 p:0152 s:0136 E:ffffee90 METHOD /builddir/build/BUILD/puma-3.9.1/usr/share/gems/gems/puma-3.9.1/lib/puma/server.rb:314
c:0024 p:0039 s:0130 E:fffff098 METHOD /builddir/build/BUILD/puma-3.9.1/usr/share/gems/gems/puma-3.9.1/test/test_puma_server.rb:402
...
```

lib/puma/reactor.rb:152
```
      @thread = Thread.new do
        begin
          run_internal
        rescue StandardError => e
          STDERR.puts "Error in reactor loop escaped: #{e.message} (#{e.class})"
          STDERR.puts e.backtrace
          retry
        ensure
          @trigger.close
          @ready.close
        end
      end
```

Do you have any idea to fix this?
Thank you.

**Comment by NikolayRys** [comment]
Thanks for the bug report, I believe that's related to the memory layout specific to this architecture.
That's fixable, I'll try to get it working this weekend.

**Comment by junaruga** [comment]
Thanks! I appreciate it.

**Comment by NikolayRys** [comment]
It turns out, the fix required complex investigation to make the gem able to support ARM architecture. 
Unfortunately, the need in this gem is not sufficient to invest in this kind of work, since the ruby 2.2 support ends in a month, so for everybody the best solution would be just update the interpreter version.
However, thanks again for you report, I've added a disclaimer about that to the readme file.
