### ISSUE TITLE
More detail in readme about versions

### ISSUE THREAD

**Issue by jjb** [NickolasVashchenko/stopgap_13632#5]
Hi,

First of all thank you so much for all the research and work that it took to find and fix this problem!

The readme says "The mentioned versions are currently most recent ones"

Ruby is now a 2.4.2. Is the bug fixed in 2.4.2 or do we still need this gem to fix it?

Maybe the readme can have a sentence explaining in which version(s) (if any) the bug has been fixed.

**Comment by NikolayRys** [comment]
Thanks for reporting that. 
They were most recent ones on the moment when readme was created. Give me a day or two, I'll figure out if 2.4.2 needs the fix and update the readme and/or gem itself.

**Comment by NikolayRys** [comment]
New versions - 2.4.2 and 2.3.5 are fine and do not need this gem. I'll update the readme.
Closing.

**Comment by jjb** [comment]
💃
